// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BilgeHotel.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250103234657_loginEdit")]
    partial class loginEdit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BilgeHotel.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BilgeHotel.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlySalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShiftEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ShiftStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("BilgeHotel.Models.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MonthlySalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("BilgeHotel.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("BilgeHotel.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RoomId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("BilgeHotel.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<bool>("HasAirConditioning")
                        .HasColumnType("bit");

                    b.Property<bool>("HasBalcony")
                        .HasColumnType("bit");

                    b.Property<bool>("HasHairdryer")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMinibar")
                        .HasColumnType("bit");

                    b.Property<bool>("HasTV")
                        .HasColumnType("bit");

                    b.Property<bool>("HasWiFi")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("MaintenanceStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 3,
                            Floor = 1,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 300m,
                            RoomType = "Üç Kişilik"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 3,
                            Floor = 1,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 300m,
                            RoomType = "Üç Kişilik"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 3,
                            Floor = 1,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 300m,
                            RoomType = "Üç Kişilik"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 3,
                            Floor = 1,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 300m,
                            RoomType = "Üç Kişilik"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 3,
                            Floor = 1,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 300m,
                            RoomType = "Üç Kişilik"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 3,
                            Floor = 1,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 300m,
                            RoomType = "Üç Kişilik"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 3,
                            Floor = 1,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 300m,
                            RoomType = "Üç Kişilik"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 3,
                            Floor = 1,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 300m,
                            RoomType = "Üç Kişilik"
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 3,
                            Floor = 1,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 300m,
                            RoomType = "Üç Kişilik"
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 3,
                            Floor = 1,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 300m,
                            RoomType = "Üç Kişilik"
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 1,
                            Floor = 1,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 150m,
                            RoomType = "Tek Kişilik"
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 1,
                            Floor = 1,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 150m,
                            RoomType = "Tek Kişilik"
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 1,
                            Floor = 1,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 150m,
                            RoomType = "Tek Kişilik"
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 1,
                            Floor = 1,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 150m,
                            RoomType = "Tek Kişilik"
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 1,
                            Floor = 1,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 150m,
                            RoomType = "Tek Kişilik"
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 1,
                            Floor = 1,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 150m,
                            RoomType = "Tek Kişilik"
                        },
                        new
                        {
                            Id = 17,
                            Capacity = 1,
                            Floor = 1,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 150m,
                            RoomType = "Tek Kişilik"
                        },
                        new
                        {
                            Id = 18,
                            Capacity = 1,
                            Floor = 1,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 150m,
                            RoomType = "Tek Kişilik"
                        },
                        new
                        {
                            Id = 19,
                            Capacity = 1,
                            Floor = 1,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 150m,
                            RoomType = "Tek Kişilik"
                        },
                        new
                        {
                            Id = 20,
                            Capacity = 1,
                            Floor = 1,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 150m,
                            RoomType = "Tek Kişilik"
                        },
                        new
                        {
                            Id = 21,
                            Capacity = 2,
                            Floor = 2,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 250m,
                            RoomType = "İki Kişilik"
                        },
                        new
                        {
                            Id = 22,
                            Capacity = 2,
                            Floor = 2,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 250m,
                            RoomType = "İki Kişilik"
                        },
                        new
                        {
                            Id = 23,
                            Capacity = 2,
                            Floor = 2,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 250m,
                            RoomType = "İki Kişilik"
                        },
                        new
                        {
                            Id = 24,
                            Capacity = 2,
                            Floor = 2,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 250m,
                            RoomType = "İki Kişilik"
                        },
                        new
                        {
                            Id = 25,
                            Capacity = 2,
                            Floor = 2,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 250m,
                            RoomType = "İki Kişilik"
                        },
                        new
                        {
                            Id = 26,
                            Capacity = 2,
                            Floor = 2,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 250m,
                            RoomType = "İki Kişilik"
                        },
                        new
                        {
                            Id = 27,
                            Capacity = 2,
                            Floor = 2,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 250m,
                            RoomType = "İki Kişilik"
                        },
                        new
                        {
                            Id = 28,
                            Capacity = 2,
                            Floor = 2,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 250m,
                            RoomType = "İki Kişilik"
                        },
                        new
                        {
                            Id = 29,
                            Capacity = 2,
                            Floor = 2,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 250m,
                            RoomType = "İki Kişilik"
                        },
                        new
                        {
                            Id = 30,
                            Capacity = 2,
                            Floor = 2,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 250m,
                            RoomType = "İki Kişilik"
                        },
                        new
                        {
                            Id = 31,
                            Capacity = 1,
                            Floor = 2,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 150m,
                            RoomType = "Tek Kişilik"
                        },
                        new
                        {
                            Id = 32,
                            Capacity = 1,
                            Floor = 2,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 150m,
                            RoomType = "Tek Kişilik"
                        },
                        new
                        {
                            Id = 33,
                            Capacity = 1,
                            Floor = 2,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 150m,
                            RoomType = "Tek Kişilik"
                        },
                        new
                        {
                            Id = 34,
                            Capacity = 1,
                            Floor = 2,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 150m,
                            RoomType = "Tek Kişilik"
                        },
                        new
                        {
                            Id = 35,
                            Capacity = 1,
                            Floor = 2,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 150m,
                            RoomType = "Tek Kişilik"
                        },
                        new
                        {
                            Id = 36,
                            Capacity = 1,
                            Floor = 2,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 150m,
                            RoomType = "Tek Kişilik"
                        },
                        new
                        {
                            Id = 37,
                            Capacity = 1,
                            Floor = 2,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 150m,
                            RoomType = "Tek Kişilik"
                        },
                        new
                        {
                            Id = 38,
                            Capacity = 1,
                            Floor = 2,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 150m,
                            RoomType = "Tek Kişilik"
                        },
                        new
                        {
                            Id = 39,
                            Capacity = 1,
                            Floor = 2,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 150m,
                            RoomType = "Tek Kişilik"
                        },
                        new
                        {
                            Id = 40,
                            Capacity = 1,
                            Floor = 2,
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasHairdryer = true,
                            HasMinibar = false,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 150m,
                            RoomType = "Tek Kişilik"
                        },
                        new
                        {
                            Id = 41,
                            Capacity = 2,
                            Floor = 3,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 350m,
                            RoomType = "İki Kişilik"
                        },
                        new
                        {
                            Id = 42,
                            Capacity = 2,
                            Floor = 3,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 350m,
                            RoomType = "İki Kişilik"
                        },
                        new
                        {
                            Id = 43,
                            Capacity = 2,
                            Floor = 3,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 350m,
                            RoomType = "İki Kişilik"
                        },
                        new
                        {
                            Id = 44,
                            Capacity = 2,
                            Floor = 3,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 350m,
                            RoomType = "İki Kişilik"
                        },
                        new
                        {
                            Id = 45,
                            Capacity = 2,
                            Floor = 3,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 350m,
                            RoomType = "İki Kişilik"
                        },
                        new
                        {
                            Id = 46,
                            Capacity = 2,
                            Floor = 3,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 350m,
                            RoomType = "İki Kişilik"
                        },
                        new
                        {
                            Id = 47,
                            Capacity = 2,
                            Floor = 3,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 350m,
                            RoomType = "İki Kişilik"
                        },
                        new
                        {
                            Id = 48,
                            Capacity = 2,
                            Floor = 3,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 350m,
                            RoomType = "İki Kişilik"
                        },
                        new
                        {
                            Id = 49,
                            Capacity = 2,
                            Floor = 3,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 350m,
                            RoomType = "İki Kişilik"
                        },
                        new
                        {
                            Id = 50,
                            Capacity = 2,
                            Floor = 3,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 350m,
                            RoomType = "İki Kişilik"
                        },
                        new
                        {
                            Id = 51,
                            Capacity = 3,
                            Floor = 3,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 450m,
                            RoomType = "Aile Odası"
                        },
                        new
                        {
                            Id = 52,
                            Capacity = 3,
                            Floor = 3,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 450m,
                            RoomType = "Aile Odası"
                        },
                        new
                        {
                            Id = 53,
                            Capacity = 3,
                            Floor = 3,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 450m,
                            RoomType = "Aile Odası"
                        },
                        new
                        {
                            Id = 54,
                            Capacity = 3,
                            Floor = 3,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 450m,
                            RoomType = "Aile Odası"
                        },
                        new
                        {
                            Id = 55,
                            Capacity = 3,
                            Floor = 3,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 450m,
                            RoomType = "Aile Odası"
                        },
                        new
                        {
                            Id = 56,
                            Capacity = 3,
                            Floor = 3,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 450m,
                            RoomType = "Aile Odası"
                        },
                        new
                        {
                            Id = 57,
                            Capacity = 3,
                            Floor = 3,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 450m,
                            RoomType = "Aile Odası"
                        },
                        new
                        {
                            Id = 58,
                            Capacity = 3,
                            Floor = 3,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 450m,
                            RoomType = "Aile Odası"
                        },
                        new
                        {
                            Id = 59,
                            Capacity = 3,
                            Floor = 3,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 450m,
                            RoomType = "Aile Odası"
                        },
                        new
                        {
                            Id = 60,
                            Capacity = 3,
                            Floor = 3,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 450m,
                            RoomType = "Aile Odası"
                        },
                        new
                        {
                            Id = 61,
                            Capacity = 3,
                            Floor = 4,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 500m,
                            RoomType = "İki Kişilik + Tek Kişilik"
                        },
                        new
                        {
                            Id = 62,
                            Capacity = 3,
                            Floor = 4,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 500m,
                            RoomType = "İki Kişilik + Tek Kişilik"
                        },
                        new
                        {
                            Id = 63,
                            Capacity = 3,
                            Floor = 4,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 500m,
                            RoomType = "İki Kişilik + Tek Kişilik"
                        },
                        new
                        {
                            Id = 64,
                            Capacity = 3,
                            Floor = 4,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 500m,
                            RoomType = "İki Kişilik + Tek Kişilik"
                        },
                        new
                        {
                            Id = 65,
                            Capacity = 3,
                            Floor = 4,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 500m,
                            RoomType = "İki Kişilik + Tek Kişilik"
                        },
                        new
                        {
                            Id = 66,
                            Capacity = 3,
                            Floor = 4,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 500m,
                            RoomType = "İki Kişilik + Tek Kişilik"
                        },
                        new
                        {
                            Id = 67,
                            Capacity = 3,
                            Floor = 4,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 500m,
                            RoomType = "İki Kişilik + Tek Kişilik"
                        },
                        new
                        {
                            Id = 68,
                            Capacity = 3,
                            Floor = 4,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 500m,
                            RoomType = "İki Kişilik + Tek Kişilik"
                        },
                        new
                        {
                            Id = 69,
                            Capacity = 3,
                            Floor = 4,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 500m,
                            RoomType = "İki Kişilik + Tek Kişilik"
                        },
                        new
                        {
                            Id = 70,
                            Capacity = 3,
                            Floor = 4,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 500m,
                            RoomType = "İki Kişilik + Tek Kişilik"
                        },
                        new
                        {
                            Id = 71,
                            Capacity = 4,
                            Floor = 4,
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasHairdryer = true,
                            HasMinibar = true,
                            HasTV = true,
                            HasWiFi = true,
                            IsAvailable = true,
                            PricePerNight = 1000m,
                            RoomType = "Kral Dairesi"
                        });
                });

            modelBuilder.Entity("BilgeHotel.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHoliday")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOvertime")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ShiftEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ShiftStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShiftType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("BilgeHotel.Models.Payment", b =>
                {
                    b.HasOne("BilgeHotel.Models.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("BilgeHotel.Models.Reservation", b =>
                {
                    b.HasOne("BilgeHotel.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BilgeHotel.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("BilgeHotel.Models.Shift", b =>
                {
                    b.HasOne("BilgeHotel.Models.Employee", "Employee")
                        .WithMany("Shifts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("BilgeHotel.Models.Employee", b =>
                {
                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
